[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
pharmatrace = "4rJojVK6QajDMFy14dpyKomvjJp3DLhkNHRpB1gygY7e"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
